name: selenium tests

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up selenium python
      uses: actions/setup-python@v2
      with:
          python-version: "3.10"
    - name: Install software
      run: sudo apt-get install -y chromium-browser
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-html
    - name: Run Unit Test
      run: |
        python -m unittest discover -s tests
    - name: Ready for deploy
      run: echo "Ready"